### ISSUE TITLE
Error in VS Code output 

### ISSUE THREAD

**Issue by ScottSlaughterBBNA** [likec4/likec4#195]
![image](https://github.com/likec4/likec4/assets/136729466/53ceb352-99b6-456c-856a-4269c4656385)

Getting this message immediately when opening any .c4 file. I've tried the example files and the most basic files I can create with no luck. The plugin appears to not work on any .c4 file.

**Comment by davydkov** [comment]
Hey @ScottSlaughterBBNA, Wow, interesting,thanks for report.

Can you please turn on verbose mode and share stack trace?

And what vscode/OS/Node version do you have?

**Comment by ScottSlaughterBBNA** [comment]
OS is Windows 10 Enterprise. Running VS Code version 1.79.2. I have node.js version 20.3.1 installed, but the about in VS code is showing 16.17.1 which doesn't even show in my NVM list as an installed version.

2023-07-06 13:26:31.951 [error] Error: Attempted to send error data when the @vscode/extension-telemetry module does not support it.
	at AS.sendErrorData (c:\Users\user\.vscode\extensions\likec4.likec4-vscode-0.27.0\dist\node.js:48:64615)
	at D.logError (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:41178)
	at e.ExtHostTelemetry.onExtensionError (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:39646)
	at c.a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:478)
	at c.onUnexpectedError (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:7:249)
	at O (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:7:603)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:33610

**Comment by davydkov** [comment]
Maybe fixed by #192, going to release a new version

**Comment by ScottSlaughterBBNA** [comment]
Just tried it with version 0.28.0 but I'm still seeing that generic error.

2023-07-06 14:17:17.473 [error] [likec4.likec4-vscode] provider FAILED
2023-07-06 14:17:17.473 [error] Error: Request textDocument/documentSymbol failed with message: Cannot access 'a' before initialization
	at handleResponse (c:\Users\user\.vscode\extensions\likec4.likec4-vscode-0.28.0\dist\node.js:11:233)
	at handleMessage (c:\Users\user\.vscode\extensions\likec4.likec4-vscode-0.28.0\dist\node.js:10:7945)
	at processMessageQueue (c:\Users\user\.vscode\extensions\likec4.likec4-vscode-0.28.0\dist\node.js:10:8101)
	at Immediate.<anonymous> (c:\Users\user\.vscode\extensions\likec4.likec4-vscode-0.28.0\dist\node.js:10:7807)
	at process.processImmediate (node:internal/timers:466:21)

**Comment by davydkov** [comment]
Thanks, I will try to reproduce and run windows in vm. 

Just wonder, web versions, like [github.dev](https://github.dev/likec4/example-cloud-system/blob/main/model.c4) or [vscode.dev](https://vscode.dev/github/likec4/example-cloud-system/blob/main/model.c4) - do they work fine on your side?

**Comment by ScottSlaughterBBNA** [comment]
I haven't tried vscode.dev, but it works fine at github.dev.

**Comment by ScottSlaughterBBNA** [comment]
I take that back. After a minute of the window open I had the same error in the browser.

[Error - 3:11:35 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot access 'o' before initialization
  Code: -32603 
["DEBUG" - 3:11:35 PM] receive: onDidChangeModel
["DEBUG" - 3:11:36 PM] fetchModel

**Comment by davydkov** [comment]
And do you use model from the example?

**Comment by ScottSlaughterBBNA** [comment]
Yes. Just selected the model.c4

![image](https://github.com/likec4/likec4/assets/136729466/033f4197-5e5e-485e-8078-a1a2c9204d15)

**Comment by ScottSlaughterBBNA** [comment]
After reloading the page a few times and slowly clicking through the .c4 files the error happens specifically when the _spec.c4 file is opened.

**Comment by davydkov** [comment]
Oh! Got the same!
Gosh, already spined Virtual Machine on Azure.

**Comment by davydkov** [comment]
Hey @ScottSlaughterBBNA Thank you for your time and your interest in finding the cause, really appreciate it.
Gonna release a new version
